#!/usr/bin/env python3
"""Rasterizes the SVG icons in
package/batocera/utils/circuitsword-quickmenu/icons/src/ into
package/batocera/utils/circuitsword-quickmenu/qm_icon_data.c.

Developer-run only -- NOT part of the Buildroot build, NOT invoked by any
.mk file. Re-run whenever a source icon is added or replaced, then commit
the diff to qm_icon_data.c alongside the source SVG change.

Requires (one-time, on the developer's machine):
    pip install cairosvg pillow
"""
import io
import os

import cairosvg
from PIL import Image

ICON_SIZE = 24
TITLE_W = 200
TITLE_H = 28

# (C enum member name, source SVG filename in icons/src/, width, height)
ICONS = [
    ("QM_ICON_BATTERY_EMPTY", "battery-empty.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_BATTERY_25", "battery-25.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_BATTERY_50", "battery-50.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_BATTERY_75", "battery-75.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_BATTERY_FULL", "battery-full.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_BATTERY_CHARGING", "battery-charging.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_WIFI", "wifi.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_VOLUME", "volume.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_VOLUME_MUTE", "volume-mute.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_VOLUME_LOW", "volume-low.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_BRIGHTNESS", "brightness.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_JOYSTICK", "joystick.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_SETTINGS", "settings.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_TOGGLE_ON", "toggle-on.svg", 32, 16),
    ("QM_ICON_TOGGLE_OFF", "toggle-off.svg", 32, 16),
    ("QM_ICON_TITLE", "title.svg", TITLE_W, TITLE_H),
    ("QM_ICON_BADGE_A", "badge-a.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_BADGE_B", "badge-b.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_BADGE_LEFT", "badge-left.svg", ICON_SIZE, ICON_SIZE),
    ("QM_ICON_BADGE_RIGHT", "badge-right.svg", ICON_SIZE, ICON_SIZE),
]

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(
    REPO_ROOT, "package/batocera/utils/circuitsword-quickmenu/icons/src")
OUT_FILE = os.path.join(
    REPO_ROOT, "package/batocera/utils/circuitsword-quickmenu/qm_icon_data.c")


def rasterize_alpha(svg_path, width, height):
    png_bytes = cairosvg.svg2png(
        url=svg_path, output_width=width, output_height=height)
    img = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
    if img.size != (width, height):
        raise ValueError(
            f"{svg_path}: rasterized to {img.size}, expected "
            f"({width}, {height})")
    return [img.getpixel((x, y))[3]
            for y in range(height) for x in range(width)]


def main():
    lines = [
        "/* Generated by tools/convert-icons.py -- DO NOT EDIT BY HAND.",
        " * Re-run the script and commit the diff to update an icon. */",
        '#include "quickmenu.h"',
        "",
    ]

    for name, filename, width, height in ICONS:
        alpha = rasterize_alpha(os.path.join(SRC_DIR, filename), width, height)
        var = f"qm_icon_alpha_{name.lower()}"
        lines.append(f"static const uint8_t {var}[{width * height}] = {{")
        for row in range(height):
            row_vals = alpha[row * width:(row + 1) * width]
            lines.append("    " + ",".join(str(v) for v in row_vals) + ",")
        lines.append("};")
        lines.append("")

    lines.append("const qm_icon_asset qm_icon_assets[QM_ICON_COUNT] = {")
    for name, _, width, height in ICONS:
        var = f"qm_icon_alpha_{name.lower()}"
        lines.append(f"    [{name}] = {{ {width}, {height}, {var} }},")
    lines.append("};")
    lines.append("")

    with open(OUT_FILE, "w") as f:
        f.write("\n".join(lines))

    print(f"wrote {OUT_FILE} ({len(ICONS)} icons)")


if __name__ == "__main__":
    main()
